name: Test Install On Windows
on:
  workflow_dispatch:
  # remove branch when merged
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.8]
    name: Python ${{ matrix.python-version }} Installation for Synthpop ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: myenv
          python-version: ${{ matrix.python-version }}
          
      - name: Use Miniconda to install
        run: | 
          python --version
          which python
          python setup.py develop
      
 
